# Fixed categories (order matters)
categories:
  - "Architecture"
  - "PipelineR"
  - "PolicyR"
  - "TrustR"
  - "AssessR"
  - "ApplyR"

# Tools
tools:
- repo: "Minimal-Finite-Covering"
    mainfile: "README.html"
    name: "Minimal-Finite-Covering # Display name (optional if you want prettier)
    category: "GreenR"
    branch: "main"
    readme_path: "docs/README.md"
    docs_root: "docs"
  - repo: "GeneralArchitecture"
    mainfile: "README.html"
    name: "General Architecture"       # Display name (optional if you want prettier)
    category: "Architecture"
    branch: "main"
    readme_path: "docs/README.md"
    docs_root: "docs"
  - repo: "FEL"
    mainfile: "README.html"
    name: "FEL"       # Display name (optional if you want prettier)
    category: "TrustR"
    branch: "main"
    readme_path: "docs/README.md"
    docs_root: "docs"
  - repo: "LLAC"
    mainfile: "README.html"
    name: "LLAC"       # Display name (optional if you want prettier)
    category: "TrustR"
    branch: "main"
    readme_path: "docs/README.md"
    docs_root: "docs"
  - repo: "RepuLink"
    mainfile: "README.html"
    name: "RepuLink"       # Display name (optional if you want prettier)
    category: "TrustR"
    branch: "main"
    readme_path: "docs/README.md"
    docs_root: "docs"
  - repo: "Guardrails"
    mainfile: "README.html"
    name: "Guardrails"       # Display name (optional if you want prettier)
    category: "TrustR"
    branch: "main"
    readme_path: "docs/README.md"
    docs_root: "docs"
  - repo: "AILegalAssistant"
    mainfile: "README.html"
    name: "AILegalAssistant"       # Display name (optional if you want prettier)
    category: "AssessR"
    branch: "main"
    readme_path: "docs/README.md"
    docs_root: "docs"
  - repo: "inLUMEN"
    mainfile: "README.html"
    name: "inLumen"       # Display name (optional if you want prettier)
    category: "PipelineR"
    branch: "main"
    readme_path: "docs/README.md"
    docs_root: "docs"
  - repo: "DPIA-Support"
    mainfile: "README.html"
    name: "DPIA Support"       # Display name (optional if you want prettier)
    category: "AssessR"
    branch: "main"
    readme_path: "docs/README.md"
    docs_root: "docs"
  - repo: "Policy-Editor"
    mainfile: "README.html"
    name: "Policy Editor"
    category: "PolicyR"
    branch: "main"
    readme_path: "docs/README.md"
    docs_root: "docs"
  - repo: "Consent-Manager"
    mainfile: "README.html"
    name: "Consent-Manager"
    category: "TrustR"
    branch: "main"
    readme_path: "docs/README.md"
    docs_root: "docs"
  - repo: "PolicyEngine"
    mainfile: "README.html"
    name: "PolicyEngine"
    category: "PolicyR"
    branch: "main"
    readme_path: "docs/README.md"
    docs_root: "docs"
  - repo: "Negotiation-tool"
    mainfile: "README.html"
    name: "Negotiation tool"
    category: "PolicyR"
    branch: "main"
    readme_path: "docs/README.md"
    docs_root: "docs"
  - repo: "DAVE"
    mainfile: "README.html"
    name: "DAVE"
    category: "PipelineR"      # Display name defaults to repo name if not set
    branch: "main"
    readme_path: "docs/README.md"
    docs_root: "docs"
  - repo: "KubePipe"
    mainfile: "README.html"
    name: "KubePipe"
    category: "PipelineR"      # Display name defaults to repo name if not set
    branch: "main"
    readme_path: "docs/README.md"
    docs_root: "docs"
  - repo: "SIMPIPE"
    mainfile: "README.html"
    name: "SIMPIPE"
    category: "PipelineR"      # Display name defaults to repo name if not set
    branch: "main"
    readme_path: "docs/README.md"
    docs_root: "docs"
  - repo: "SEMT-X"
    mainfile: "README.html"
    name: "SEMT-X"
    category: "PipelineR"      # Display name defaults to repo name if not set
    branch: "main"
    readme_path: "docs/README.md"
    docs_root: "docs"
  - repo: "Wikifier"
    mainfile: "README.html"
    name: "Wikifier"
    category: "PipelineR"      # Display name defaults to repo name if not set
    branch: "main"
    readme_path: "docs/README.md"
    docs_root: "docs"    
  - repo: "LexAlign"
    mainfile: "README.html"
    category: "AssessR"      # Display name defaults to repo name if not set
    branch: "main"
    readme_path: "docs/README.md"
    docs_root: "docs"
  - repo: "toolbox-ui"
    mainfile: "README.html"
    category: "ApplyR"      # Display name defaults to repo name if not set
    branch: "main"
    readme_path: "docs/README.md"
    docs_root: "docs"

