# Fixed categories (order matters)
categories:
  - "Architecture"
  - "PipelineR"
  - "PolicyR"
  - "TrustR"
  - "GreenR"
  - "AssessR"
  - "ApplyR"
# Tools
tools:
#Architecture
  - repo: "GeneralArchitecture"
    mainfile: "README.html"
    name: "General Architecture"       # Display name (optional if you want prettier)
    category: "Architecture"
    branch: "main"
    readme_path: "docs/README.md"
    docs_root: "docs"
#PipelineR
  - repo: "inLUMEN"
    mainfile: "README.html"
    name: "inLumen"       # Display name (optional if you want prettier)
    category: "PipelineR"
    branch: "main"
    readme_path: "docs/README.md"
    docs_root: "docs"
  - repo: "KubePipe"
    mainfile: "README.html"
    name: "KubePipe"
    category: "PipelineR"     
    branch: "main"
    readme_path: "docs/README.md"
    docs_root: "docs"
  - repo: "SIM-PIPE"
    mainfile: "README.html"
    name: "SIM-PIPE"
    category: "PipelineR"      
    branch: "main"
    readme_path: "docs/README.md"
    docs_root: "docs"
  - repo: "SEMT-X"
    mainfile: "README.html"
    name: "SEMT-X"
    category: "PipelineR"     
    branch: "main"
    readme_path: "docs/README.md"
    docs_root: "docs"
  - repo: "counteR-pseudonymization-tool"
    mainfile: "README.html"
    name: "counteR"
    category: "PipelineR"      
    branch: "main"
    readme_path: "docs/README.md"
    docs_root: "docs"   
#PolicyR
  - repo: "Policy-Editor"
    mainfile: "README.html"
    name: "Policy Editor"
    category: "PolicyR"
    branch: "main"
    readme_path: "docs/README.md"
    docs_root: "docs"
  - repo: "PolicyEngine"
    mainfile: "README.html"
    name: "PolicyEngine"
    category: "PolicyR"
    branch: "main"
    readme_path: "docs/README.md"
    docs_root: "docs"
  - repo: "Negotiation-tool"
    mainfile: "README.html"
    name: "Negotiation tool"
    category: "PolicyR"
    branch: "main"
    readme_path: "docs/README.md"
    docs_root: "docs"
#TrustR
  - repo: "Minimal-Finite-Covering"
    mainfile: "README.html"
    name: "Compresso" # Display name (optional if you want prettier)
    category: "TrustR"
    branch: "main"
    readme_path: "docs/README.md"
    docs_root: "docs"
  - repo: "FEL"
    mainfile: "README.html"
    name: "FEL"       # Display name (optional if you want prettier)
    category: "TrustR"
    branch: "main"
    readme_path: "docs/README.md"
    docs_root: "docs"
  - repo: "RepuLink"
    mainfile: "README.html"
    name: "RepuLink"       # Display name (optional if you want prettier)
    category: "TrustR"
    branch: "main"
    readme_path: "docs/README.md"
    docs_root: "docs"
  - repo: "Guardrails"
    mainfile: "README.html"
    name: "Guardrails"       # Display name (optional if you want prettier)
    category: "TrustR"
    branch: "main"
    readme_path: "docs/README.md"
    docs_root: "docs"
  - repo: "ITACA"
    mainfile: "README.html"
    name: "ITACA"       # Display name (optional if you want prettier)
    category: "TrustR"
    branch: "main"
    readme_path: "docs/README.md"
    docs_root: "docs"
  - repo: "Consent-Manager"
    mainfile: "README.html"
    name: "Consent Manager"
    category: "TrustR"
    branch: "main"
    readme_path: "docs/README.md"
    docs_root: "docs"
  - repo: "DAVE"
    mainfile: "README.html"
    name: "DAVE"
    category: "TrustR"     
    branch: "main"
    readme_path: "docs/README.md"
    docs_root: "docs"
#GreenR
  - repo: "CarbonTracker"
    mainfile: "README.html"
    name: "CarbonTracker"
    category: "GreenR"     
    branch: "main"
    readme_path: "docs/README.md"
    docs_root: "docs"
#AssessR
  - repo: "LLAC"
    mainfile: "README.html"
    name: "LLAC"       # Display name (optional if you want prettier)
    category: "AssessR"
    branch: "main"
    readme_path: "docs/README.md"
    docs_root: "docs"
  - repo: "AILegalAssistant"
    mainfile: "README.html"
    name: "AILegalAssistant"       # Display name (optional if you want prettier)
    category: "AssessR"
    branch: "main"
    readme_path: "docs/README.md"
    docs_root: "docs"
  - repo: "DPIA-Support"
    mainfile: "README.html"
    name: "DPIA Support"       # Display name (optional if you want prettier)
    category: "AssessR"
    branch: "main"
    readme_path: "docs/README.md"
    docs_root: "docs"
  - repo: "LexAlign"
    mainfile: "README.html"
    name: "LexAlign"  # Display name defaults to repo name if not set
    category: "AssessR"     
    branch: "main"
    readme_path: "docs/README.md"
    docs_root: "docs"
#ApplyR
  - repo: "alligator"
    mainfile: "README.html"
    name: "Alligator"       # Display name (optional if you want prettier)
    category: "ApplyR"
    branch: "main"
    readme_path: "docs/README.md"
    docs_root: "docs"
  - repo: "lion_linker"
    mainfile: "README.html"
    name: "LionLinker"       # Display name (optional if you want prettier)
    category: "ApplyR"
    branch: "main"
    readme_path: "docs/README.md"
    docs_root: "docs"
  - repo: "crocodile"
    mainfile: "README.html"
    name: "Crocodile"       # Display name (optional if you want prettier)
    category: "ApplyR"
    branch: "main"
    readme_path: "docs/README.md"
    docs_root: "docs"
  - repo: "Wikifier"
    mainfile: "README.html"
    name: "Wikifier"     # Display name defaults to repo name if not set
    category: "ApplyR"      
    branch: "main"
    readme_path: "docs/README.md"
    docs_root: "docs" 
  - repo: "toolbox-ui"
    mainfile: "README.html"
    name: "toolbox-ui"     
    category: "ApplyR"     
    branch: "main"
    readme_path: "docs/README.md"
    docs_root: "docs"

    
















  
  


